### ISSUE TITLE
로깅용 graylog docker-compose.yml

### ISSUE THREAD

**Issue by PracticeofEno** [42tv/backend#1]
graylog 공홈에서 뭔가 연결이 잘 안되서 연결되게 수정함
graylog가 필요할시 해당 파일 복붙해서 실행하면 됨

```
version: '3'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: "mongo:6.0.18"
    container_name: test_mongo
    ports:
      - "27017:27017"   
    # restart: "on-failure"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "POeb9s9uYkp8Eq70"
    networks:
      - graylog
    volumes:
      - "mongodb_data:/data/db"
      - "mongodb_config:/data/configdb"  
  #Graylog Data Node: https://hub.docker.com/r/graylog/graylog-datanode
  datanode:
    depends_on:
      mongodb:
        condition: "service_started"
    image: "graylog/graylog-datanode:6.1"
    container_name: "datanode"
    environment:
      GRAYLOG_DATANODE_NODE_ID_FILE: "/var/lib/graylog-datanode/node-id"
      GRAYLOG_DATANODE_ROOT_USERNAME: "admin"
      GRAYLOG_DATANODE_PASSWORD_SECRET: "POeb9s9uYkp8Eq70"
      GRAYLOG_DATANODE_ROOT_PASSWORD_SHA2: "6dfb928bf6dcf0246f4f24d0530532b95e9b38ace4900ee753c582640a22998e"
      GRAYLOG_DATANODE_MONGODB_URI: "mongodb://admin:POeb9s9uYkp8Eq70@test_mongo:27017/graylog?authSource=admin"
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "8999:8999/tcp"   # DataNode API
      - "9200:9200/tcp"
      - "9300:9300/tcp"
    networks:
      - graylog  
    volumes:
      - "graylog-datanode:/var/lib/graylog-datanode"
    # restart: "on-failure"  
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    hostname: "server"
    image: "graylog/graylog-enterprise:6.1"
    # To install Graylog Open: "graylog/graylog:6.1"
    depends_on:
      mongodb:
        condition: "service_started"
      datanode:
        condition: "service_started"
    entrypoint: "/usr/bin/tini -- /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/config/node-id"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_MONGODB_URI: "mongodb://admin:POeb9s9uYkp8Eq70@test_mongo:27017/graylog?authSource=admin"
      # To make reporting (headless_shell) work inside a Docker container
      GRAYLOG_REPORT_DISABLE_SANDBOX: "true"
      # CHANGE ME (must be at least 16 characters)!
      GRAYLOG_PASSWORD_SECRET: "POeb9s9uYkp8Eq70"
      # Password: "admin"
      GRAYLOG_ROOT_PASSWORD_SHA2: "6dfb928bf6dcf0246f4f24d0530532b95e9b38ace4900ee753c582640a22998e"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://127.0.0.1:9000/"
    ports:
      # Graylog web interface and REST API
      - "9000:9000/tcp"
      # Beats
      - "5044:5044/tcp"
      # Syslog TCP
      - "5140:5140/tcp"
      # Syslog UDP
      - "5140:5140/udp"
      # GELF TCP
      - "12201:12201/tcp"
      # GELF UDP
      - "12201:12201/udp"
      # Forwarder data
      - "13301:13301/tcp"
      # Forwarder config
      - "13302:13302/tcp"
    # restart: "on-failure"
    networks:
      - graylog
    volumes:
      - "graylog_data:/usr/share/graylog/data"
  redis:
    image: "redis"
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - "./redis.conf:/usr/local/etc/redis/redis.conf"

networks:
  graylog:
    driver: "bridge"
volumes:
  mongodb_data:
  mongodb_config:
  graylog-datanode:
  graylog_data:
```
